### ISSUE TITLE
Allow all attributes of the specific tag

### ISSUE THREAD

**Issue by pd4d10** [syntax-tree/hast-util-sanitize#17]
### Subject of the feature

Sometimes we may need to allow all attributes of the specific tag. Could we add a rule like this?

```js
const schema = {
  tagNames: ['svg'],
  attributes: [
    { svg: '*' } // Allow all attributes of svg tag
  ]
}
```

### Alternatives

The alternative way is to add [all possible attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute), which could be too complicated and will cause large bundle size in the browser.

**Comment by wooorm** [comment]
That would be incredibly unsafe. The whole goal of this project is to keep you safe. If you really want to enable all incredibly dangerous possibilities, then why use this project at all? 🤷‍♂️

**Comment by pd4d10** [comment]
Thanks for the quick response.

I'm not sure, is there any insecure SVG attribute?

The real-world use case is [rehype-katex](https://github.com/remarkjs/remark-math/tree/master/packages/rehype-katex#use). KaTeX would render some elements as SVG, for example:

```math
\sqrt{a}
```

So if we want to keep the final result sanitized, we should decide how to handle SVG.

**Comment by pd4d10** [comment]
Perhaps the correct way is to review KaTeX's source code and find out which tags and attributes are used?

**Comment by wooorm** [comment]
> I'm not sure, is there any insecure SVG attribute?

Mostly the JavaScript event handlers are dangerous on the `<svg>` element: https://svgwg.org/svg2-draft/types.html#InterfaceSVGElement. However, there are more insecure attributes on other SVG elements.

> So if we want to keep the final result sanitized, we should decide how to handle SVG.

Correct, and that’s the goal of this project: it prohibits everything, except if you specifically allow things.

> Perhaps the correct way is to review KaTeX's source code and find out which tags and attributes are used?

If you trust the content, don’t use this project. If you don’t trust the content, you must specifically list what you allow.

---

I’ll close this here, because I think the defaults make sense.
